# Generated by Django 3.0.2 on 2020-01-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('fachschaftszitat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024)),
                ('order_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fachschaftszitat.Author')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='statements',
            field=models.ManyToManyField(to='fachschaftszitat.Statement'),
        ),
    ]
