# Generated by Django 2.0.1 on 2018-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=1024, unique=True)),
                ('timestamp', models.DateField()),
                ('authors', models.ManyToManyField(to='fachschaftszitat.Author')),
            ],
        ),
    ]
