# Generated by Django 2.0.1 on 2018-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fachschaftszitat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
