version: "2"

networks:
 pg_db:
  internal: true

services:
 quotesapp:
  image: zitate:0.1
  build:
   context: .
   dockerfile: Dockerfile
  networks:
    - default
    - pg_db
  volumes:
   - ./fachschaftszitat:/fs_zitat
  env_file:
   - docker.env
  ports:
   - 8888:80

 dbzitate:
  image: postgres:10-alpine
  networks:
   - pg_db
  volumes:
   - ./data/pgdata/:/var/lib/postgresql/data/
  env_file:
   - docker.env

